name: Auto-merge approved PRs

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: 🤖 Auto-merge approved PRs
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'

    steps:
      - name: 🤖 Enable auto-merge for approved PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            
            try {
              // Enable auto-merge with squash
              await github.rest.pulls.enableAutoMerge({
                owner,
                repo,
                pull_number,
                merge_method: 'squash'
              });
              
              console.log(`Auto-merge enabled for PR #${pull_number}`);
              
              // Add auto-merge label
              await github.rest.issues.addLabels({
                issue_number: pull_number,
                owner,
                repo,
                labels: ['auto-merge']
              });
              
            } catch (error) {
              console.error('Failed to enable auto-merge:', error.message);
            } 